apiVersion: batch/v1
kind: CronJob
metadata:
  name: servicenow-warranty-updater
  namespace: default
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'servicenow-warranty-updater'
            vault.hashicorp.com/agent-inject-secret-main-secrets: 'concourse/main'
            vault.hashicorp.com/agent-inject-template-main-secrets: |
              {{- with secret "concourse/main" -}}
                export SERVICENOW_INSTANCE='{{ index .Data.data "snow-instance" }}'
                export SERVICENOW_CI_TABLE_PATH='{{ index .Data.data "snow-ci-table-path" }}'
              {{- end }}
            vault.hashicorp.com/agent-inject-secret-servicenow-warranty-updater-secrets: 'concourse/main/servicenow-warranty-updater'
            vault.hashicorp.com/agent-inject-template-servicenow-warranty-updater-secrets: |
              {{- with secret "concourse/main/servicenow-warranty-updater" -}}
                export SERVICENOW_USERNAME='{{ index .Data.data "snow-username" }}'
                export SERVICENOW_PASSWORD='{{ index .Data.data "snow-password" }}'
                export CISCO_CLIENT_KEY='{{ index .Data.data "cisco-client-key" }}'
                export CISCO_CLIENT_SECRET='{{ index .Data.data "cisco-client-secret" }}'
                export CISCO_AUTH_TOKEN_URI='{{ index .Data.data "cisco-auth-token-uri" }}'
                export CISCO_WARRANTY_URI='{{ index .Data.data "cisco-warranty-uri" }}'
                export CISCO_EOX_URI='{{ index .Data.data "cisco-eox-uri" }}'
                export DELL_CLIENT_KEY='{{ index .Data.data "dell-client-key" }}'
                export DELL_CLIENT_SECRET='{{ index .Data.data "dell-client-secret" }}'
                export DELL_AUTH_TOKEN_URI='{{ index .Data.data "dell-auth-token-uri" }}'
                export DELL_WARRANTY_URI='{{ index .Data.data "dell-warranty-uri" }}'
              {{- end }}
            vault.hashicorp.com/ca-cert: /run/secrets/kubernetes.io/serviceaccount/ca.crt
            vault.hashicorp.com/agent-pre-populate-only: "true"
        spec:
          containers:
            - image: registry.quokka.ninja/ccfs/servicenow-warranty-updater:2.0.15
              imagePullPolicy: Always
              name: servicenow-warranty-updater
              args: ['/bin/bash', '-c', 'source /vault/secrets/main-secrets && source /vault/secrets/servicenow-warranty-updater-secrets && python ./src/ServiceNow-Warranty-Updater.py']
          imagePullSecrets:
            - name: gitlab-cr
          restartPolicy: Never
          serviceAccountName: servicenow-warranty-updater
      backoffLimit: 3
  schedule: 0 13 * * 0
